module.exports = [
    // TODO: Add student videos

    {
        name: "Reyna Jansen",
        bio: "",
        photo: "ReynaJansen.jpg",
        website: "https://moonmakesart.wixsite.com/gallery",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Racyn Noguchi",
        bio: "",
        photo: "racyn-noguchi.jpg",
        website: "https://sites.google.com/view/webdemoreeldemosite/home",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "DyLin Khoe",
        bio: "",
        photo: "DylinKhoe.jpg",
        website: "https://st3gmolak.wixsite.com/steg",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Aden Kemp",
        bio: "",
        photo: "AdenKemp.jpg",
        website: "https://sites.google.com/hawaii.edu/aok/home",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Bridgette Laranio",
        bio: "",
        photo: "BridgetteLaranio.jpg",
        website: "https://sites.google.com/view/blaranio/home",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Adrianremoh Mangahis",
        bio: "",
        photo: "AdrianremohMangahis.jpg",
        website: "https://sites.google.com/view/adrianremohmangahis/home",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Luis Pascua",
        bio: "",
        photo: "JoseLuisPascua.jpg",
        website: "https://sites.google.com/view/luispascua/home",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Jake Camara",
        bio: "",
        photo: "JakeCamara.jpg",
        website: "http://jscamara.com/",
        demoreel: "",
        specialization: "Animation",
    },
    {
        name: "Crystal Kim",
        bio: "",
        photo: "HyeLimKim.jpg",
        website: "https://sites.google.com/hawaii.edu/rystql/art-gallery/3d",
        demoreel: "",
        specialization: "Animation",
    },

];